# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae82e432b4299a5f2446a8b5cc42e86cb6ce5828a55d932c5734a3b884e4fd50f6d50cde87a36360f19bedf071d8af18552073310eec0a569a594c8baa87990c

test:
  secret_key_base: 97e38b1691364f8ec3a47e49fd9f6838d3a0cc0aa8bfb03d6c0d6496612d3de193fbe8e2161cdfd84dea8b3e25308ef8b4d5bb8bdb19396029e5a9b1f54c8215

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
